name: Best practices for source files

on:
  pull_request:
    branches:
      - master

jobs:
  check-bom:
    name: No BOMs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for BOMs
        uses: arma-actions/bom-check@v1.0

  check-crlf:
    name: No CRLF endings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for CRLF endings
        uses: erclu/check-crlf@v1
